name: Anwendung mit Pyinstaller packen

on:
  push:
#    tags:
#      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./

    - uses: actions/upload-artifact@v2
      with:
        name: pythonExeTest
        path: dist/windows

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/windows/Flughafen.exe
        file_glob: false
        tag: ${{ github.ref }}
        overwrite: true
